---
monitoring_project_dir: /opt/monitoring
monitoring_compose_project_name: devops-monitoring

monitoring_loki_version: "3.0.0"
monitoring_promtail_version: "3.0.0"
monitoring_grafana_version: "12.3.1"

monitoring_loki_port: 3100
monitoring_promtail_port: 9080
monitoring_grafana_port: 3000
monitoring_app_port: 8000
monitoring_app_internal_port: 8000

monitoring_loki_retention_period: "168h"
monitoring_grafana_admin_user: admin
monitoring_grafana_admin_password: ChangeMe_Lab07!
monitoring_grafana_datasource_uid: loki
monitoring_grafana_datasource_name: Loki

monitoring_app_service_name: app-python
monitoring_app_container_name: devops-python
monitoring_app_label: devops-python
monitoring_app_image: devops-info-service:lab07
monitoring_app_source_dir: "{{ playbook_dir }}/../../app_python"
monitoring_app_source_files:
  - .dockerignore
  - Dockerfile
  - requirements.txt
  - app.py
monitoring_app_env:
  HOST: "0.0.0.0"
  PORT: "{{ monitoring_app_internal_port | string }}"
  DEBUG: "false"

monitoring_resource_limits:
  loki:
    limits: { cpus: '1.0', memory: 1G }
    reservations: { cpus: '0.25', memory: 256M }
  promtail:
    limits: { cpus: '0.75', memory: 512M }
    reservations: { cpus: '0.10', memory: 128M }
  grafana:
    limits: { cpus: '1.0', memory: 1G }
    reservations: { cpus: '0.25', memory: 256M }
  app_python:
    limits: { cpus: '0.75', memory: 512M }
    reservations: { cpus: '0.10', memory: 128M }
