[webservers]
vagrant1 ansible_host=172.19.144.1 ansible_port=2222 ansible_user=vagrant ansible_ssh_private_key_file=/home/dorley/.ssh/lab05_vagrant_key

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
