apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info-service
  namespace: devops-lab09
  labels:
    app.kubernetes.io/name: devops-info-service
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: devops-core-course
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-info-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-info-service
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: devops-core-course
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: devops-info-service
          image: dorley174/devops-info-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: PORT
              value: "5000"
            - name: DEBUG
              value: "False"
            - name: APP_VARIANT
              value: "app1"
            - name: APP_MESSAGE
              value: "Lab 09 primary deployment"
            - name: SERVICE_VERSION
              value: "lab09-v1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
